In [3]:
#numpy.asarray(a, dtype = None, order = None)
# 将tuple转换为 ndarray 
import numpy as np 

x =  (1,2,3)
a = np.asarray(x)  
print(a)

# 设置了 dtype  
import numpy as np 

x =  [1,2,3] 
a = np.asarray(x, dtype =  float)  
print (a)

# 来自元组列表的 ndarray
import numpy as np 

x =  [(1,2,3),(4,5)] 
a = np.asarray(x)  
print (a)

# 将列表转换为 ndarray 
import numpy as np 

x =  [1,2,3] 
a = np.asarray(x)  
print (a)

[1 2 3]
[1. 2. 3.]
[(1, 2, 3) (4, 5)]
[1 2 3]


In [6]:
#numpy.fromiter(iterable, dtype, count = -1)
#此函数从任何可迭代对象构建一个ndarray对象，返回一个新的一维数组。
# 从列表中获得迭代器  
import numpy as np 
list = range(5) 
it = iter(list)  
# 使用迭代器创建 ndarray 
x = np.fromiter(it, dtype =  float) 
print(x)

[0. 1. 2. 3. 4.]


In [7]:
#numpy.arange(start, stop, step, dtype)
# 设置了起始值和终止值参数  
import numpy as np
x = np.arange(10,20,2)  
print(x)

[10 12 14 16 18]


In [8]:
#numpy.linspace(start, stop, num, endpoint, retstep, dtype)
#endpoint 序列中是否包含stop值，默认为ture
#retstep 如果为true，返回样例，以及连续数字之间的步长
# 输出 retstep 值  
import numpy as np

x = np.linspace(1,2,5, retstep =  True)  
print(x)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
