In [5]:
#NumPy 包包含一个迭代器对象numpy.nditer

import numpy as np
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print  ('原始数组是：' ) 
print (a) 
a=a.T
print  ('修改后的数组是：' ) 
for x in np.nditer(a,order='C'):  #C cols  F rows
    print(x)

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
修改后的数组是：
0
20
40
5
25
45
10
30
50
15
35
55


In [8]:
#numpy.ndarray.flat
#该函数返回数组上的一维迭代器，行为类似 Python 内建的迭代器
import numpy as np
a = np.arange(8).reshape(2,4)
print(a)
print(a.flat[5])

[[0 1 2 3]
 [4 5 6 7]]
5


In [7]:
#numpy.ndarray.flatten
#该函数返回折叠为一维的数组副本，函数接受下列参数
#order：'C' — 按行，'F' — 按列，'A' — 原顺序，'k' — 元素在内存中的出现顺序。
print(a.flatten(order='F'))

[0 4 1 5 2 6 3 7]


In [9]:
#numpy.transpose(arr, axes)  
#arr：要转置的数组
# axes：整数的列表，对应维度，通常所有维度都会翻转。
print(np.transpose(a))

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [15]:
#numpy.rollaxis(arr, axis, start)
#arr：输入数组 axis：要向后滚动的轴，其它轴的相对位置不会改变
# start：默认为零，表示完整的滚动。会滚动到特定位置。

# 创建了三维的 ndarray
import numpy as np
a = np.arange(8).reshape(2,2,2)

print (a)
print('\n')
# 将轴 2 滚动到轴 0(宽度到深度)

print (np.rollaxis(a,2) ) 
# 将轴 0 滚动到轴 1：(宽度到高度)'

print (np.rollaxis(a,2,1))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]
