In [8]:
#numpy.sort(a, axis, kind, order)
#a 要排序的数组 axis 沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序
# kind 默认为'quicksort'(快速排序)
# order 如果数组包含字段，则是要排序的字段

import numpy as np
a=np.array([[3,7],[9,1]])
print(np.sort(a,0))

dt=np.dtype([('name','S10'),('age',int)])
b=np.array([('pay',12),('ali',14),('koko',5)],dtype=dt)
print(np.sort(b,order='name'))

[[3 1]
 [9 7]]
[(b'ali', 14) (b'koko',  5) (b'pay', 12)]


In [11]:
#numpy.argsort()函数对输入数组沿给定轴执行间接排序，并使用指定排序类型返回数据的索引数组
x=np.array([3,1,5])
y=np.argsort(x)
print(y)
print(x[y])
for i in y:
    print(x[i])

[1 0 2]
[1 3 5]
1
3
5


In [ ]:
#两个函数分别沿给定轴返回最大和最小元素的索引

#numpy.argmax() 和 numpy.argmin()

In [12]:
#numpy.nonzero()函数返回输入数组中非零元素的索引
a = np.array([[30,40,0],[0,20,10],[50,0,60]]) 
print(np.nonzero(a))

(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))


In [14]:
#where()函数返回输入数组中满足给定条件的元素的索引。
x = np.arange(9.).reshape(3,  3)  
print(x)
y=np.where(x>5)
print(y)
for i in y:
    print(x[y])

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
(array([2, 2, 2]), array([0, 1, 2]))
[6. 7. 8.]
[6. 7. 8.]


In [15]:
#extract()函数返回满足任何条件的元素。
condition=np.mod(x,2)==0
print(condition)
print(np.extract(condition,x))

[[ True False  True]
 [False  True False]
 [ True False  True]]
[0. 2. 4. 6. 8.]
