In [ ]:
#NumPy 包包含numpy.linalg模块，提供线性代数所需的所有功能。

In [1]:
#此函数返回两个数组的点积。
import numpy as np
import numpy.matlib
a=np.array([[1,2],[1,2]])
b=np.array([[2,1],[2,1]])
print(np.dot(a,b))

[[6 3]
 [6 3]]


In [2]:
#此函数返回两个向量的点积。 如果第一个参数是复数，那么它的共轭复数会用于计算。 如果参数id是多维数组，它会被展开。
print(np.vdot(a,b))

8


In [3]:
#此函数返回一维数组的向量内积。 对于更高的维度，它返回最后一个轴上的和的乘积。
print(np.inner(np.array([1,2,3]),np.array([0,1,0])))

2


In [11]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
print(a)
print('\n')
print(b)
print('\n')
print(np.inner(a,b))
# 1*11+2*12, 1*13+2*14 
# 3*11+4*12, 3*13+4*14

[[1 2]
 [3 4]]


[[11 12]
 [13 14]]


[[35 41]
 [81 95]]


In [12]:
#numpy.matmul()函数返回两个数组的矩阵乘积。
print(np.matmul(a,b))

[[37 40]
 [85 92]]


In [15]:
#对于矩阵[[a，b]，[c，d]]，行列式计算为ad-bc。 较大的方阵被认为是 2×2 矩阵的组合。
c=np.array([[3,2],[3,4]])
print(np.linalg.det(c))

6.0


In [ ]:
#numpy.linalg.solve()函数给出了矩阵形式的线性方程的解。

In [ ]:
#使用numpy.linalg.inv()函数来计算矩阵的逆。 

In [19]:
#NumPy - IO
#numpy.save()文件将输入数组存储在具有npy扩展名的磁盘文件中。
encoding='utf-8'
a=np.array([1,2,3,4,5])
np.save('outfile',a)

In [20]:
#为了从outfile.npy重建数组，请使用load()函数。
b=np.load('outfile.npy')
print(b)

[1 2 3 4 5]
