In [ ]:
#NumPy 有很多有用的统计函数，用于从数组中给定的元素中查找最小，最大，百分标准差和方差等

In [4]:
#这些函数从给定数组中的元素沿指定轴返回最小值和最大值
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]])  
print(a)
print(np.amin(a,0),np.amin(a,1))# 0--cols 1--rows
print(np.amax(a))
print(np.amax(a,0),np.amax(a,1))

[[3 7 5]
 [8 4 3]
 [2 4 9]]
[2 4 3] [3 3 2]
9
[8 7 9] [7 8 9]


In [6]:
#numpy.ptp()函数返回沿轴的值的范围(最大值 - 最小值)
print(np.ptp(a,0))

[6 3 6]


In [7]:
# 中值定义为将数据样本的上半部分与下半部分分开的值
print(np.median(a,0))

[3. 4. 5.]


In [9]:
#算术平均值是沿轴的元素的总和除以元素的数量\
print(np.mean(a,0))

[4.33333333 5.         5.66666667]


In [11]:
#加权平均值是由每个分量乘以反映其重要性的因子得到的平均值
a = np.array([1,2,3,4])
print(np.average(a))
print(np.average(a,weights=np.array([4,3,2,1])))

2.5
2.0


In [12]:
#标准差是与均值的偏差的平方的平均值的平方根
#std = sqrt(mean((x - x.mean())**2))
print(np.std(a))

1.118033988749895


In [13]:
# 方差是偏差的平方的平均值，即mean((x - x.mean())** 2)。 换句话说，标准差是方差的平方根。
print(np.var(a))

1.25
