In [1]:
#NumPy 拥有标准的三角函数
import numpy as np
a = np.array([0,30,45,60,90])
print(np.sin(a*np.pi/180))
print(np.cos(a*np.pi/180))
print(np.tan(a*np.pi/180))

#arcsin，arccos，和arctan函数返回给定角度的sin，cos和tan的反三角函数

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [2]:
# numpy.around(a,decimals) 这个函数返回四舍五入到所需精度的值
#decimals 要舍入的小数位数。 默认值为0。 如果为负，整数将四舍五入到小数点左侧的位置
a = np.array([1.0,5.55,  123,  0.567,  25.532]) 
print(np.around(a))
print(np.around(a,decimals=1))
print(np.around(a,decimals=-1))

[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


In [3]:
#此函数返回不大于输入参数的最大整数。
a = np.array([-1.7,  1.5,  -0.2,  0.6,  10])  
print(np.floor(a))

[-2.  1. -1.  0. 10.]


In [4]:
#ceil()函数返回输入值的上限，即，标量x的上限是最小的整数i
print(np.ceil(a))

[-1.  2. -0.  1. 10.]


In [9]:
#执行算术运算(如add()，subtract()，multiply()和divide())的输入数组必须具有相同的形状或符合数组广播规则
a=np.arange(9).reshape(3,3)
b=np.arange(3)
print(a,b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]] [0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]
[[0 0 0]
 [3 3 3]
 [6 6 6]]
[[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]]


In [10]:
#此函数返回参数逐元素的倒数
a=np.array([1.5,5,2.5])
print(np.reciprocal(a))

[0.66666667 0.2        0.4       ]


In [12]:
#此函数将第一个输入数组中的元素作为底数，计算它与第二个输入数组中相应元素的幂。
a = np.array([10,100,1000])  
print(np.power(a,2))
b=[1,2,3]
print(np.power(a,b))

[    100   10000 1000000]
[        10      10000 1000000000]


In [13]:
#此函数返回输入数组中相应元素的除法余数。 函数numpy.remainder()也产生相同的结果。
print(np.mod(a,b))

[0 0 1]
