In [ ]:
#NumPy 包包含一个 Matrix库numpy.matlib。此模块的函数返回矩阵而不是返回ndarray对象


In [1]:
#numpy.matlib.empty(shape, dtype, order)
import numpy as np
import numpy.matlib
print(np.matlib.empty((2,2))) ## 填充为随机数据

[[ 4.66292769e-310 -9.05779341e-105]
 [ 6.91916108e-310  4.00193173e-322]]


In [2]:
#此函数返回以零填充的矩阵。
print(np.matlib.zeros((2,2))) 

[[0. 0.]
 [0. 0.]]


In [3]:
#此函数返回以一填充的矩阵。
print(np.matlib.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [6]:
#这个函数返回一个矩阵，对角线元素为 1，其他位置为零。 该函数接受以下参数。
#numpy.matlib.eye(n, M,k, dtype)
#n 行数  M 列数，默认为n k 对角线的索引  
print(np.matlib.eye(n=2,M=4,k=2))

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
#numpy.matlib.identity()函数返回给定大小的单位矩阵。单位矩阵是主对角线元素都为 1 的方阵。
print(np.matlib.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
#numpy.matlib.rand()`函数返回给定大小的填充随机值的矩阵。
print(np.matlib.rand(2,3))

[[0.29262478 0.64294304 0.19960217]
 [0.04721541 0.81818775 0.0379874 ]]


In [9]:
i=np.matrix('1,2;3,4;5,6')
print(i)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
j=np.asarray(i)
print(j)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
k=np.asmatrix(j)
print(k)

[[1 2]
 [3 4]
 [5 6]]
